# These are supported funding model platforms

github: [Junseo5]
# patreon: # patreon_username
# open_collective: # open_collective_username
# ko_fi: # ko_fi_username
# tidelift: # npm/package-name
# community_bridge: # project-name
# liberapay: # liberapay_username
# issuehunt: # issuehunt_username
# lfx_crowdfunding: # project-name
# polar: # polar_username
# buy_me_a_coffee: # buy_me_a_coffee_username
# custom: []
