import { describe, expect, it } from 'vitest';
import { detectCaptionDocumentFormat, parseCaptionDocument } from './captionParsers';

describe('captionParsers', () => {
  it('parses SRT documents into timed segments', () => {
    const result = parseCaptionDocument(
      `1
00:00:01,000 --> 00:00:03,500
Hello world

2
00:00:04,000 --> 00:00:06,000
Second line one
Second line two`,
      'srt',
    );

    expect(result).toEqual([
      { startTime: 1, endTime: 3.5, text: 'Hello world' },
      { startTime: 4, endTime: 6, text: 'Second line one\nSecond line two' },
    ]);
  });

  it('parses VTT documents and strips formatting tags', () => {
    const result = parseCaptionDocument(
      `WEBVTT

intro
00:00:01.000 --> 00:00:03.000
<v Alice><b>Hello</b> world</v>`,
      'vtt',
    );

    expect(result).toEqual([{ startTime: 1, endTime: 3, text: 'Hello world', speaker: 'Alice' }]);
  });

  it('strips inline tags from SRT documents', () => {
    const result = parseCaptionDocument(
      `1
00:00:01,000 --> 00:00:03,000
<font color="red"><i>Hello</i></font>
<b>world</b>`,
      'srt',
    );

    expect(result).toEqual([{ startTime: 1, endTime: 3, text: 'Hello\nworld' }]);
  });

  it('skips WebVTT metadata blocks before parsing cues', () => {
    const result = parseCaptionDocument(
      `WEBVTT

NOTE generated by subtitle editor
keep this metadata

STYLE
::cue { color: lime; }

REGION
id:bottom

intro
00:00:01.000 --> 00:00:03.000
First cue`,
      'vtt',
    );

    expect(result).toEqual([{ startTime: 1, endTime: 3, text: 'First cue' }]);
  });

  it('detects caption document format from file extension and content', () => {
    expect(detectCaptionDocumentFormat('captions/scene.srt')).toBe('srt');
    expect(detectCaptionDocumentFormat('captions/scene.vtt')).toBe('vtt');
    expect(detectCaptionDocumentFormat('captions/scene.txt', 'WEBVTT\n\n')).toBe('vtt');
  });
});
