//! Agent Plan Types
//!
//! Defines the data structures for the backend agent plan executor.
//! These types are serialized to TypeScript via specta for frontend IPC.

use serde::{Deserialize, Serialize};

// =============================================================================
// Plan Input Types (Frontend → Backend)
// =============================================================================

/// A plan produced by the AI planner, consisting of ordered steps
/// to be executed atomically with rollback support.
#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct AgentPlan {
    /// Unique plan identifier
    pub id: String,
    /// Human-readable goal description
    pub goal: String,
    /// Ordered steps to execute
    pub steps: Vec<PlanStep>,
    /// Whether user approval was granted before execution
    pub approval_granted: bool,
    /// Session ID for tracing
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
}

/// A single step within an agent plan.
#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct PlanStep {
    /// Step identifier (e.g., "step-1")
    pub id: String,
    /// Tool/command name to execute (maps to a Command type)
    pub tool_name: String,
    /// Arguments for the tool as flexible JSON
    pub params: serde_json::Value,
    /// Human-readable step description
    pub description: String,
    /// Risk level of this step
    pub risk_level: PlanRiskLevel,
    /// IDs of steps that must complete before this one
    #[serde(default)]
    pub depends_on: Vec<String>,
    /// Whether this step can be skipped on failure
    #[serde(default)]
    pub optional: bool,
}

/// Risk level for plan steps.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "lowercase")]
pub enum PlanRiskLevel {
    Low,
    Medium,
    High,
    Critical,
}

// =============================================================================
// Execution Result Types (Backend → Frontend)
// =============================================================================

/// Result of executing an entire agent plan.
#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct AgentPlanResult {
    /// Plan identifier
    pub plan_id: String,
    /// Whether all steps completed successfully
    pub success: bool,
    /// Total number of steps in the plan
    pub total_steps: usize,
    /// Number of steps that completed successfully
    pub steps_completed: usize,
    /// Individual step results
    pub step_results: Vec<StepResult>,
    /// Operation IDs generated by the command executor (for undo)
    pub operation_ids: Vec<String>,
    /// Rollback report if recovery was attempted
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rollback_report: Option<RollbackReport>,
    /// Error message if execution failed
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    /// Total execution time in milliseconds
    pub execution_time_ms: u64,
}

/// Result of executing a single plan step.
#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct StepResult {
    /// Step identifier
    pub step_id: String,
    /// Whether the step succeeded
    pub success: bool,
    /// Result data from the tool (available for $fromStep resolution)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    /// Error message if the step failed
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// Execution duration in milliseconds
    pub duration_ms: u64,
    /// Operation ID generated by the command executor
    #[serde(skip_serializing_if = "Option::is_none")]
    pub operation_id: Option<String>,
}

/// Report of rollback operations after a plan failure.
#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct RollbackReport {
    /// Whether rollback was attempted
    pub attempted: bool,
    /// ID of the step that failed and triggered rollback
    pub failed_step_id: String,
    /// Index of the failed step in the plan
    pub failed_at_index: usize,
    /// Number of completed steps that were candidates for rollback
    pub candidate_count: usize,
    /// Number of rollback operations attempted
    pub attempted_count: usize,
    /// Number of rollback operations that succeeded
    pub succeeded_count: usize,
    /// Number of rollback operations that failed
    pub failed_count: usize,
    /// Step IDs that were rolled back (in reverse execution order)
    pub rolled_back_steps: Vec<String>,
    /// Errors encountered during rollback
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub rollback_errors: Vec<String>,
    /// Reason if rollback was not attempted
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

// =============================================================================
// Unit Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn agent_plan_serialization_roundtrip() {
        let plan = AgentPlan {
            id: "plan-001".to_string(),
            goal: "Split clip at 5 seconds".to_string(),
            steps: vec![PlanStep {
                id: "step-1".to_string(),
                tool_name: "split_clip".to_string(),
                params: serde_json::json!({
                    "clipId": "clip-1",
                    "splitTime": 5.0
                }),
                description: "Split clip at position 5s".to_string(),
                risk_level: PlanRiskLevel::Low,
                depends_on: vec![],
                optional: false,
            }],
            approval_granted: true,
            session_id: Some("session-1".to_string()),
        };

        let json = serde_json::to_string(&plan).unwrap();
        let deserialized: AgentPlan = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.id, "plan-001");
        assert_eq!(deserialized.steps.len(), 1);
        assert_eq!(deserialized.steps[0].tool_name, "split_clip");
        assert!(deserialized.approval_granted);
    }

    #[test]
    fn agent_plan_result_serialization_roundtrip() {
        let result = AgentPlanResult {
            plan_id: "plan-001".to_string(),
            success: true,
            total_steps: 2,
            steps_completed: 2,
            step_results: vec![
                StepResult {
                    step_id: "step-1".to_string(),
                    success: true,
                    data: Some(serde_json::json!({ "newClipId": "clip-2" })),
                    error: None,
                    duration_ms: 42,
                    operation_id: Some("op-001".to_string()),
                },
                StepResult {
                    step_id: "step-2".to_string(),
                    success: true,
                    data: None,
                    error: None,
                    duration_ms: 18,
                    operation_id: Some("op-002".to_string()),
                },
            ],
            operation_ids: vec!["op-001".to_string(), "op-002".to_string()],
            rollback_report: None,
            error_message: None,
            execution_time_ms: 60,
        };

        let json = serde_json::to_string(&result).unwrap();
        let deserialized: AgentPlanResult = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.plan_id, "plan-001");
        assert!(deserialized.success);
        assert_eq!(deserialized.steps_completed, 2);
        assert_eq!(deserialized.operation_ids.len(), 2);
        assert!(deserialized.rollback_report.is_none());
    }

    #[test]
    fn rollback_report_serialization_roundtrip() {
        let report = RollbackReport {
            attempted: true,
            failed_step_id: "step-2".to_string(),
            failed_at_index: 1,
            candidate_count: 1,
            attempted_count: 1,
            succeeded_count: 1,
            failed_count: 0,
            rolled_back_steps: vec!["step-1".to_string()],
            rollback_errors: vec![],
            reason: None,
        };

        let json = serde_json::to_string(&report).unwrap();
        let deserialized: RollbackReport = serde_json::from_str(&json).unwrap();

        assert!(deserialized.attempted);
        assert_eq!(deserialized.failed_step_id, "step-2");
        assert_eq!(deserialized.succeeded_count, 1);
        assert!(deserialized.rollback_errors.is_empty());
    }

    #[test]
    fn plan_risk_level_serialization() {
        let low = serde_json::to_string(&PlanRiskLevel::Low).unwrap();
        assert_eq!(low, "\"low\"");

        let critical = serde_json::to_string(&PlanRiskLevel::Critical).unwrap();
        assert_eq!(critical, "\"critical\"");

        let from_json: PlanRiskLevel = serde_json::from_str("\"high\"").unwrap();
        assert_eq!(from_json, PlanRiskLevel::High);
    }

    #[test]
    fn camel_case_field_names_in_json() {
        let step = PlanStep {
            id: "s1".to_string(),
            tool_name: "split_clip".to_string(),
            params: serde_json::json!({}),
            description: "Split".to_string(),
            risk_level: PlanRiskLevel::Low,
            depends_on: vec!["s0".to_string()],
            optional: false,
        };

        let json = serde_json::to_string(&step).unwrap();
        assert!(json.contains("\"toolName\""));
        assert!(json.contains("\"riskLevel\""));
        assert!(json.contains("\"dependsOn\""));
        assert!(!json.contains("\"tool_name\""));
    }
}
